### ISSUE TITLE
AttributeError("'Page' object has no attribute 'client'")

### ISSUE THREAD

**Issue by vardaan123** [web-arena-x/visualwebarena#38]
While running the evaluation for Classifieds (also for reddit), I get the error `Page' object has no attribute 'client'`. The stack trace is shown below (also happens for config_files/test_classifieds/211.json). Did you face this issue? Any suggestion to fix this is highly appreciated.

```
[Config file]: config_files/test_classifieds/117.json
[Unhandled Error] AttributeError("'Page' object has no attribute 'client'")
Traceback (most recent call last):
  File "/home/pahuja.9/visualwebarena/run.py", line 396, in test
    obs, _, terminated, _, info = env.step(action)
  File "/home/pahuja.9/visualwebarena/browser_env/envs.py", line 307, in step
    observation = self._get_obs()
  File "<@beartype(browser_env.envs.ScriptBrowserEnv._get_obs) at 0x7f1a3d76e200>", line 10, in _get_obs
  File "/home/pahuja.9/visualwebarena/browser_env/envs.py", line 226, in _get_obs
    self.page, self.get_page_client(self.page)
  File "<@beartype(browser_env.envs.ScriptBrowserEnv.get_page_client) at 0x7f1a3d76e050>", line 33, in get_page_client
  File "/home/pahuja.9/visualwebarena/browser_env/envs.py", line 221, in get_page_client
    return page.client  # type: ignore
AttributeError: 'Page' object has no attribute 'client'
```

**Comment by kohjingyu** [comment]
I think this happens if the agent navigates to an invalid page (e.g., a blank page in a new tab), which is pretty infrequent in my experience. Did that happen in this particular trajectory?

**Comment by vardaan123** [comment]
Yes, looks like. It happened for 2/234 tasks in Classifieds and 4/210 tasks in Reddit. Should I ignore it?

**Comment by kohjingyu** [comment]
I think it's ok to ignore it for now, though if I have time I'll see if I can find a solution to it. For tasks that ended as such in our baselines we marked them as failures.
