### ISSUE TITLE
'devicePixelRatio is not 1.0' when running run_demo.py

### ISSUE THREAD

**Issue by EvgenyKos** [web-arena-x/visualwebarena#6]
Hi,

A browser opens and then just closes. Getting this message:

[Unhandled Error] AssertionError('devicePixelRatio is not 1.0')].

Could you advise?

**Comment by kohjingyu** [comment]
We've not seen this message, can you share the full error trace? It should be part of `error.txt` in the output directory.

**Comment by EvgenyKos** [comment]
Of course, here it is:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Evgeny\Documents\GitHub\visualwebarena\run_demo.py", line 321, in test
    obs, info = env.reset(options={"config_file": config_file})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(browser_env.envs.ScriptBrowserEnv.reset) at 0x22e280deca0>", line 51, in reset
  File "C:\Users\Evgeny\Documents\GitHub\visualwebarena\browser_env\envs.py", line 264, in reset
    observation = self._get_obs()
                  ^^^^^^^^^^^^^^^
  File "<@beartype(browser_env.envs.ScriptBrowserEnv._get_obs) at 0x22e280de980>", line 10, in _get_obs
  File "C:\Users\Evgeny\Documents\GitHub\visualwebarena\browser_env\envs.py", line 225, in _get_obs
    obs = self.observation_handler.get_observation(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(browser_env.processors.ObservationHandler.get_observation) at 0x22e26ff8040>", line 52, in get_observation
  File "C:\Users\Evgeny\Documents\GitHub\visualwebarena\browser_env\processors.py", line 1225, in get_observation
    text_obs = self.text_processor.process(page, client)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(browser_env.processors.TextObervationProcessor.process) at 0x22e26fd3560>", line 52, in process
  File "C:\Users\Evgeny\Documents\GitHub\visualwebarena\browser_env\processors.py", line 562, in process
    browser_info = self.fetch_browser_info(page, client)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(browser_env.processors.TextObervationProcessor.fetch_browser_info) at 0x22e26fd2fc0>", line 53, in fetch_browser_info
  File "C:\Users\Evgeny\Documents\GitHub\visualwebarena\browser_env\processors.py", line 117, in fetch_browser_info
    assert device_pixel_ratio == 1.0, "devicePixelRatio is not 1.0"
AssertionError: devicePixelRatio is not 1.0

**Comment by kohjingyu** [comment]
Thanks, we took a look at this but weren't sure why this is happening, since device_scale_factor is set to 1 here:

https://github.com/web-arena-x/visualwebarena/blob/715c72e22c3a447b4b78cfcaadee682b9662710c/browser_env/envs.py#L188

Could you perhaps try on a different device? The other option is you can comment out the asserts here:

https://github.com/web-arena-x/visualwebarena/blob/715c72e22c3a447b4b78cfcaadee682b9662710c/browser_env/processors.py#L117

https://github.com/web-arena-x/visualwebarena/blob/715c72e22c3a447b4b78cfcaadee682b9662710c/browser_env/processors.py#L1141

If you could also find out what devicePixelRatio is set to, that might also give a hint 😕
